[2022-11-20T00:45:14.175+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_fact_call_data manual__2022-11-20T00:44:38.455644+00:00 [queued]>
[2022-11-20T00:45:14.228+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_fact_call_data manual__2022-11-20T00:44:38.455644+00:00 [queued]>
[2022-11-20T00:45:14.230+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T00:45:14.232+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-20T00:45:14.233+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T00:45:14.361+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): insert_fact_call_data> on 2022-11-20 00:44:38.455644+00:00
[2022-11-20T00:45:14.440+0000] {standard_task_runner.py:55} INFO - Started process 3549 to run task
[2022-11-20T00:45:14.483+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'insert_fact_call_data', 'manual__2022-11-20T00:44:38.455644+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/call_center_dag.py', '--cfg-path', '/tmp/tmp5b8odmjx']
[2022-11-20T00:45:14.491+0000] {standard_task_runner.py:83} INFO - Job 144: Subtask insert_fact_call_data
[2022-11-20T00:45:15.495+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.insert_fact_call_data manual__2022-11-20T00:44:38.455644+00:00 [running]> on host 9eba6bc17a61
[2022-11-20T00:45:16.259+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=insert_fact_call_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T00:44:38.455644+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-20T00:44:38.455644+00:00
[2022-11-20T00:45:16.285+0000] {mysql.py:84} INFO - Executing: 
        INSERT INTO call_fact(call_id,customer_id,call_date,csat_score,call_in_minutes)
        SELECT DISTINCT
            st.id as call_id,
            c.customer_id ,
            STR_TO_DATE(call_timestamp, '%m/%d/%Y') AS call_date,
            CASE
                WHEN st.csat_score = ' ' THEN 1
                WHEN st.csat_score = 0 THEN 1
            END AS  csat_score,
            call_minutes
        FROM 
            staging_call st
        join customers c 
        on st.customer_name = c.customer_name
        WHERE
            id IS NOT NULL;
        
[2022-11-20T00:45:16.348+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T00:45:16.509+0000] {sql.py:315} INFO - Running statement: 
        INSERT INTO call_fact(call_id,customer_id,call_date,csat_score,call_in_minutes)
        SELECT DISTINCT
            st.id as call_id,
            c.customer_id ,
            STR_TO_DATE(call_timestamp, '%m/%d/%Y') AS call_date,
            CASE
                WHEN st.csat_score = ' ' THEN 1
                WHEN st.csat_score = 0 THEN 1
            END AS  csat_score,
            call_minutes
        FROM 
            staging_call st
        join customers c 
        on st.customer_name = c.customer_name
        WHERE
            id IS NOT NULL;
        , parameters: None
[2022-11-20T00:45:23.365+0000] {sql.py:324} INFO - Rows affected: 32941
[2022-11-20T00:45:23.590+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Call_Center_ETL_DAG, task_id=insert_fact_call_data, execution_date=20221120T004438, start_date=20221120T004514, end_date=20221120T004523
[2022-11-20T00:45:23.677+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-20T00:45:23.713+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
