[2022-11-20T13:16:02.415+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.Run_data_quality_checks manual__2022-11-20T13:15:12.651027+00:00 [queued]>
[2022-11-20T13:16:02.499+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.Run_data_quality_checks manual__2022-11-20T13:15:12.651027+00:00 [queued]>
[2022-11-20T13:16:02.502+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:16:02.514+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-20T13:16:02.516+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:16:02.633+0000] {taskinstance.py:1383} INFO - Executing <Task(DataQualityOperator): Run_data_quality_checks> on 2022-11-20 13:15:12.651027+00:00
[2022-11-20T13:16:02.668+0000] {standard_task_runner.py:55} INFO - Started process 922 to run task
[2022-11-20T13:16:02.712+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'Run_data_quality_checks', 'manual__2022-11-20T13:15:12.651027+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/call_center_dag.py', '--cfg-path', '/tmp/tmppgr3a8fw']
[2022-11-20T13:16:02.715+0000] {standard_task_runner.py:83} INFO - Job 174: Subtask Run_data_quality_checks
[2022-11-20T13:16:03.333+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.Run_data_quality_checks manual__2022-11-20T13:15:12.651027+00:00 [running]> on host 9eba6bc17a61
[2022-11-20T13:16:03.633+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=Run_data_quality_checks
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T13:15:12.651027+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-20T13:15:12.651027+00:00
[2022-11-20T13:16:03.680+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:16:03.788+0000] {data_quality.py:59} INFO - Data quality on table customers check passed with 32941 records
[2022-11-20T13:16:03.825+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:16:04.074+0000] {data_quality.py:59} INFO - Data quality on table call_fact check passed with 32941 records
[2022-11-20T13:16:04.119+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:16:04.188+0000] {data_quality.py:59} INFO - Data quality on table call_time check passed with 31 records
[2022-11-20T13:16:04.210+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:16:04.311+0000] {data_quality.py:59} INFO - Data quality on table call_info check passed with 32941 records
[2022-11-20T13:16:04.362+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Call_Center_ETL_DAG, task_id=Run_data_quality_checks, execution_date=20221120T131512, start_date=20221120T131602, end_date=20221120T131604
[2022-11-20T13:16:04.500+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-20T13:16:05.170+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
