[2022-11-20T13:11:44.995+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_call_time_data scheduled__2022-11-18T00:00:00+00:00 [queued]>
[2022-11-20T13:11:45.139+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_call_time_data scheduled__2022-11-18T00:00:00+00:00 [queued]>
[2022-11-20T13:11:45.147+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:11:45.150+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-20T13:11:45.154+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:11:45.720+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): insert_call_time_data> on 2022-11-18 00:00:00+00:00
[2022-11-20T13:11:46.000+0000] {standard_task_runner.py:55} INFO - Started process 735 to run task
[2022-11-20T13:11:46.247+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'insert_call_time_data', 'scheduled__2022-11-18T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/call_center_dag.py', '--cfg-path', '/tmp/tmpplptb9s4']
[2022-11-20T13:11:46.295+0000] {standard_task_runner.py:83} INFO - Job 155: Subtask insert_call_time_data
[2022-11-20T13:11:47.354+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.insert_call_time_data scheduled__2022-11-18T00:00:00+00:00 [running]> on host 9eba6bc17a61
[2022-11-20T13:11:48.529+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=insert_call_time_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-18T00:00:00+00:00
[2022-11-20T13:11:48.545+0000] {mysql.py:84} INFO - Executing: 
        INSERT INTO call_time(call_date,day,week,weekday, month,year)
        SELECT DISTINCT
            STR_TO_DATE(call_timestamp, '%m/%d/%Y') AS call_date,
            DAY(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS day,
            WEEK(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS week,
            DAYNAME(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS weekday,
            MONTH(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS month,
            YEAR(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS year
        FROM
            staging_call
        WHERE
            call_timestamp IS NOT NULL
        
[2022-11-20T13:11:48.698+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:11:49.016+0000] {sql.py:315} INFO - Running statement: 
        INSERT INTO call_time(call_date,day,week,weekday, month,year)
        SELECT DISTINCT
            STR_TO_DATE(call_timestamp, '%m/%d/%Y') AS call_date,
            DAY(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS day,
            WEEK(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS week,
            DAYNAME(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS weekday,
            MONTH(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS month,
            YEAR(STR_TO_DATE(call_timestamp, '%m/%d/%Y')) AS year
        FROM
            staging_call
        WHERE
            call_timestamp IS NOT NULL
        , parameters: None
[2022-11-20T13:11:49.029+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'call_center.call_time' doesn't exist")
[2022-11-20T13:11:49.195+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Call_Center_ETL_DAG, task_id=insert_call_time_data, execution_date=20221118T000000, start_date=20221120T131145, end_date=20221120T131149
[2022-11-20T13:11:49.634+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 155 for task insert_call_time_data ((1146, "Table 'call_center.call_time' doesn't exist"); 735)
[2022-11-20T13:11:49.830+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-20T13:11:50.300+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
