[2022-11-19T13:27:07.706+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.Drop_Tables manual__2022-11-19T13:26:47.742386+00:00 [queued]>
[2022-11-19T13:27:07.902+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.Drop_Tables manual__2022-11-19T13:26:47.742386+00:00 [queued]>
[2022-11-19T13:27:07.903+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T13:27:07.905+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-19T13:27:07.908+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T13:27:08.308+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): Drop_Tables> on 2022-11-19 13:26:47.742386+00:00
[2022-11-19T13:27:08.334+0000] {standard_task_runner.py:55} INFO - Started process 1195 to run task
[2022-11-19T13:27:08.364+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'Drop_Tables', 'manual__2022-11-19T13:26:47.742386+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/create_database_tables.py', '--cfg-path', '/tmp/tmpec0b4qu5']
[2022-11-19T13:27:08.365+0000] {standard_task_runner.py:83} INFO - Job 109: Subtask Drop_Tables
[2022-11-19T13:27:08.973+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.Drop_Tables manual__2022-11-19T13:26:47.742386+00:00 [running]> on host 9eba6bc17a61
[2022-11-19T13:27:10.590+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=Drop_Tables
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T13:26:47.742386+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-19T13:26:47.742386+00:00
[2022-11-19T13:27:10.599+0000] {mysql.py:84} INFO - Executing: 
    DROP TABLE IF EXISTS staging_call;
    DROP TABLE IF EXISTS call_info;
    DROP TABLE IF EXISTS call_fact;
    DROP TABLE IF EXISTS customers;
    DROP TABLE IF EXISTS call_time;
    
[2022-11-19T13:27:10.652+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-19T13:27:13.439+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 173, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2003, "Can't connect to MySQL server on 'host.docker.internal:3307' (111)")
[2022-11-19T13:27:13.465+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Call_Center_ETL_DAG, task_id=Drop_Tables, execution_date=20221119T132647, start_date=20221119T132707, end_date=20221119T132713
[2022-11-19T13:27:13.585+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 109 for task Drop_Tables ((2003, "Can't connect to MySQL server on 'host.docker.internal:3307' (111)"); 1195)
[2022-11-19T13:27:13.752+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-19T13:27:13.911+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
