[2022-11-19T12:36:22.357+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.load_data_to_staging_call_table manual__2022-11-19T12:34:04.246836+00:00 [queued]>
[2022-11-19T12:36:22.780+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.load_data_to_staging_call_table manual__2022-11-19T12:34:04.246836+00:00 [queued]>
[2022-11-19T12:36:22.801+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T12:36:22.812+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-19T12:36:22.823+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-19T12:36:23.451+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): load_data_to_staging_call_table> on 2022-11-19 12:34:04.246836+00:00
[2022-11-19T12:36:23.501+0000] {standard_task_runner.py:55} INFO - Started process 913 to run task
[2022-11-19T12:36:23.520+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'load_data_to_staging_call_table', 'manual__2022-11-19T12:34:04.246836+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/create_database_tables.py', '--cfg-path', '/tmp/tmpx9a30oka']
[2022-11-19T12:36:23.526+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask load_data_to_staging_call_table
[2022-11-19T12:36:24.255+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.load_data_to_staging_call_table manual__2022-11-19T12:34:04.246836+00:00 [running]> on host 6e77c1f44c06
[2022-11-19T12:36:25.365+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=load_data_to_staging_call_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T12:34:04.246836+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-19T12:34:04.246836+00:00
[2022-11-19T12:36:25.369+0000] {mysql.py:84} INFO - Executing: 
            LOAD DATA INFILE 'G:/docker-files/CallCenter.csv'
            INTO TABLE staging_call
            COLUMNS TERMINATED BY ','
            OPTIONALLY ENCLOSED BY '"'
            ESCAPED BY '"'
            LINES TERMINATED BY '
'
            IGNORE 1 LINES;
            
[2022-11-19T12:36:25.447+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-19T12:36:25.539+0000] {sql.py:315} INFO - Running statement: 
            LOAD DATA INFILE 'G:/docker-files/CallCenter.csv'
            INTO TABLE staging_call
            COLUMNS TERMINATED BY ','
            OPTIONALLY ENCLOSED BY '"'
            ESCAPED BY '"'
            LINES TERMINATED BY '
'
            IGNORE 1 LINES;
            , parameters: None
[2022-11-19T12:36:25.559+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1290, 'The MySQL server is running with the --secure-file-priv option so it cannot execute this statement')
[2022-11-19T12:36:25.589+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Call_Center_ETL_DAG, task_id=load_data_to_staging_call_table, execution_date=20221119T123404, start_date=20221119T123622, end_date=20221119T123625
[2022-11-19T12:36:25.701+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 95 for task load_data_to_staging_call_table ((1290, 'The MySQL server is running with the --secure-file-priv option so it cannot execute this statement'); 913)
[2022-11-19T12:36:25.804+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-19T12:36:25.979+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
